### ISSUE TITLE
Documentation and code error

### ISSUE THREAD

**Issue by mrkarlson** [vuefront/create-vuefront-app#3]
I could install it and show all products in home page, but there are error when it try recover "meta" and blog/category content/product content don't appear (there are meta error in javascript). I tried change some structure / components but I can't, anything change (I follow documentation)

I think you are updating all code and for that it doesn't work but I want to know that.

You are work is awesome, I am waitng for try it.

**Comment by dmitriyzhuk** [comment]
Hi, we have heavily reworked the component structure. here is what it will look like 

https://vuefront.github.io/vuefront/ (work in progress)

Also, the documentation is outdated and will be updated soon. 

Thank you for your interest. for more help please join our discord server https://discord.gg/C9vcTCQ
